// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_WatchFace_screen_init();
    ui_Launcher_screen_init();
    ui_QuickSettings_screen_init();
    ui_Notification_screen_init();
    ui_Settings_screen_init();
    ui_XiaoZhi_screen_init();
    ui_Music_screen_init();
    ui_Recorder_screen_init();
    ui_About_screen_init();
    ui_Boot_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_WatchFace);
}

void ui_destroy(void)
{
    ui_WatchFace_screen_destroy();
    ui_Launcher_screen_destroy();
    ui_QuickSettings_screen_destroy();
    ui_Notification_screen_destroy();
    ui_Settings_screen_destroy();
    ui_XiaoZhi_screen_destroy();
    ui_Music_screen_destroy();
    ui_Recorder_screen_destroy();
    ui_About_screen_destroy();
    ui_Boot_screen_destroy();
}
