// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef _SMARTWATCH_UI_UI_H
#define _SMARTWATCH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_WatchFace.h"
#include "screens/ui_Launcher.h"
#include "screens/ui_QuickSettings.h"
#include "screens/ui_Notification.h"
#include "screens/ui_Settings.h"
#include "screens/ui_XiaoZhi.h"
#include "screens/ui_Music.h"
#include "screens/ui_Recorder.h"
#include "screens/ui_About.h"
#include "screens/ui_Boot.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
