// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_ABOUT_H
#define UI_ABOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_About
extern void ui_About_screen_init(void);
extern void ui_About_screen_destroy(void);
extern lv_obj_t * ui_About;
// CUSTOM VARIABLES
extern lv_obj_t * uic_About;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

