// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_Boot;
lv_obj_t * ui_Boot = NULL;
// event funtions

// build funtions

void ui_Boot_screen_init(void)
{
    ui_Boot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Boot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Boot = ui_Boot;

}

void ui_Boot_screen_destroy(void)
{
    if(ui_Boot) lv_obj_del(ui_Boot);

    // NULL screen variables
    uic_Boot = NULL;
    ui_Boot = NULL;

}
