// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_Launcher;
lv_obj_t * ui_Launcher = NULL;
lv_obj_t * ui_btnxiaozhi = NULL;
lv_obj_t * ui_btnrecorder = NULL;
lv_obj_t * ui_btnmusic = NULL;
lv_obj_t * ui_btnabout = NULL;
lv_obj_t * ui_btndiagnostics = NULL;
lv_obj_t * ui_btnsettings = NULL;
// event funtions

// build funtions

void ui_Launcher_screen_init(void)
{
    ui_Launcher = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Launcher, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnxiaozhi = lv_button_create(ui_Launcher);
    lv_obj_set_width(ui_btnxiaozhi, 100);
    lv_obj_set_height(ui_btnxiaozhi, 50);
    lv_obj_set_x(ui_btnxiaozhi, -90);
    lv_obj_set_y(ui_btnxiaozhi, -161);
    lv_obj_set_align(ui_btnxiaozhi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnxiaozhi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnxiaozhi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnrecorder = lv_button_create(ui_Launcher);
    lv_obj_set_width(ui_btnrecorder, 100);
    lv_obj_set_height(ui_btnrecorder, 50);
    lv_obj_set_x(ui_btnrecorder, 110);
    lv_obj_set_y(ui_btnrecorder, -164);
    lv_obj_set_align(ui_btnrecorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnrecorder, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnrecorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnmusic = lv_button_create(ui_Launcher);
    lv_obj_set_width(ui_btnmusic, 100);
    lv_obj_set_height(ui_btnmusic, 50);
    lv_obj_set_x(ui_btnmusic, -86);
    lv_obj_set_y(ui_btnmusic, -69);
    lv_obj_set_align(ui_btnmusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnmusic, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnmusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnabout = lv_button_create(ui_Launcher);
    lv_obj_set_width(ui_btnabout, 100);
    lv_obj_set_height(ui_btnabout, 50);
    lv_obj_set_x(ui_btnabout, 112);
    lv_obj_set_y(ui_btnabout, -67);
    lv_obj_set_align(ui_btnabout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnabout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnabout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btndiagnostics = lv_button_create(ui_Launcher);
    lv_obj_set_width(ui_btndiagnostics, 100);
    lv_obj_set_height(ui_btndiagnostics, 50);
    lv_obj_set_x(ui_btndiagnostics, 112);
    lv_obj_set_y(ui_btndiagnostics, 21);
    lv_obj_set_align(ui_btndiagnostics, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndiagnostics, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btndiagnostics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnsettings = lv_button_create(ui_Launcher);
    lv_obj_set_width(ui_btnsettings, 100);
    lv_obj_set_height(ui_btnsettings, 50);
    lv_obj_set_x(ui_btnsettings, -86);
    lv_obj_set_y(ui_btnsettings, 22);
    lv_obj_set_align(ui_btnsettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnsettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Launcher = ui_Launcher;

}

void ui_Launcher_screen_destroy(void)
{
    if(ui_Launcher) lv_obj_del(ui_Launcher);

    // NULL screen variables
    uic_Launcher = NULL;
    ui_Launcher = NULL;
    ui_btnxiaozhi = NULL;
    ui_btnrecorder = NULL;
    ui_btnmusic = NULL;
    ui_btnabout = NULL;
    ui_btndiagnostics = NULL;
    ui_btnsettings = NULL;

}
