// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_LAUNCHER_H
#define UI_LAUNCHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Launcher
extern void ui_Launcher_screen_init(void);
extern void ui_Launcher_screen_destroy(void);
extern lv_obj_t * ui_Launcher;
extern lv_obj_t * ui_btnxiaozhi;
extern lv_obj_t * ui_btnrecorder;
extern lv_obj_t * ui_btnmusic;
extern lv_obj_t * ui_btnabout;
extern lv_obj_t * ui_btndiagnostics;
extern lv_obj_t * ui_btnsettings;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Launcher;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

