// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_Music;
lv_obj_t * ui_Music = NULL;
// event funtions

// build funtions

void ui_Music_screen_init(void)
{
    ui_Music = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Music = ui_Music;

}

void ui_Music_screen_destroy(void)
{
    if(ui_Music) lv_obj_del(ui_Music);

    // NULL screen variables
    uic_Music = NULL;
    ui_Music = NULL;

}
