// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_MUSIC_H
#define UI_MUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music
extern void ui_Music_screen_init(void);
extern void ui_Music_screen_destroy(void);
extern lv_obj_t * ui_Music;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Music;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

