// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_Notification;
lv_obj_t * ui_Notification = NULL;
// event funtions

// build funtions

void ui_Notification_screen_init(void)
{
    ui_Notification = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Notification, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Notification = ui_Notification;

}

void ui_Notification_screen_destroy(void)
{
    if(ui_Notification) lv_obj_del(ui_Notification);

    // NULL screen variables
    uic_Notification = NULL;
    ui_Notification = NULL;

}
