// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_NOTIFICATION_H
#define UI_NOTIFICATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Notification
extern void ui_Notification_screen_init(void);
extern void ui_Notification_screen_destroy(void);
extern lv_obj_t * ui_Notification;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Notification;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

