// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_slidervolume;
lv_obj_t * uic_sliderbrightness;
lv_obj_t * uic_QuickSettings;
lv_obj_t * ui_QuickSettings = NULL;
lv_obj_t * ui_sliderbrightness = NULL;
lv_obj_t * ui_slidervolume = NULL;
// event funtions

// build funtions

void ui_QuickSettings_screen_init(void)
{
    ui_QuickSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_QuickSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sliderbrightness = lv_slider_create(ui_QuickSettings);
    lv_slider_set_value(ui_sliderbrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sliderbrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_sliderbrightness, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_sliderbrightness, 150);
    lv_obj_set_height(ui_sliderbrightness, 10);
    lv_obj_set_x(ui_sliderbrightness, -106);
    lv_obj_set_y(ui_sliderbrightness, -178);
    lv_obj_set_align(ui_sliderbrightness, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sliderbrightness, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sliderbrightness,
                                                                                                       lv_obj_get_style_pad_right(ui_sliderbrightness, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_slidervolume = lv_slider_create(ui_QuickSettings);
    lv_slider_set_value(ui_slidervolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slidervolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_slidervolume, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_slidervolume, 150);
    lv_obj_set_height(ui_slidervolume, 10);
    lv_obj_set_x(ui_slidervolume, -105);
    lv_obj_set_y(ui_slidervolume, -75);
    lv_obj_set_align(ui_slidervolume, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_slidervolume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_slidervolume,
                                                                                                   lv_obj_get_style_pad_right(ui_slidervolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    uic_QuickSettings = ui_QuickSettings;
    uic_sliderbrightness = ui_sliderbrightness;
    uic_slidervolume = ui_slidervolume;

}

void ui_QuickSettings_screen_destroy(void)
{
    if(ui_QuickSettings) lv_obj_del(ui_QuickSettings);

    // NULL screen variables
    uic_QuickSettings = NULL;
    ui_QuickSettings = NULL;
    uic_sliderbrightness = NULL;
    ui_sliderbrightness = NULL;
    uic_slidervolume = NULL;
    ui_slidervolume = NULL;

}
