// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_QUICKSETTINGS_H
#define UI_QUICKSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_QuickSettings
extern void ui_QuickSettings_screen_init(void);
extern void ui_QuickSettings_screen_destroy(void);
extern lv_obj_t * ui_QuickSettings;
extern lv_obj_t * ui_sliderbrightness;
extern lv_obj_t * ui_slidervolume;
// CUSTOM VARIABLES
extern lv_obj_t * uic_QuickSettings;
extern lv_obj_t * uic_sliderbrightness;
extern lv_obj_t * uic_slidervolume;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

