// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_RECORDER_H
#define UI_RECORDER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Recorder
extern void ui_Recorder_screen_init(void);
extern void ui_Recorder_screen_destroy(void);
extern lv_obj_t * ui_Recorder;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Recorder;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

