// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_Recorder;
lv_obj_t * ui_Recorder = NULL;
// event funtions

// build funtions

void ui_Recorder_screen_init(void)
{
    ui_Recorder = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Recorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Recorder = ui_Recorder;

}

void ui_Recorder_screen_destroy(void)
{
    if(ui_Recorder) lv_obj_del(ui_Recorder);

    // NULL screen variables
    uic_Recorder = NULL;
    ui_Recorder = NULL;

}
