// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Settings;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

