// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_WATCHFACE_H
#define UI_WATCHFACE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WatchFace
extern void ui_WatchFace_screen_init(void);
extern void ui_WatchFace_screen_destroy(void);
extern lv_obj_t * ui_WatchFace;
extern lv_obj_t * ui_labeltime;
extern lv_obj_t * ui_labeldate;
extern lv_obj_t * ui_labelbattery;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WatchFace;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

