// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#include "../ui.h"

lv_obj_t * uic_WatchFace;
lv_obj_t * ui_WatchFace = NULL;
lv_obj_t * ui_labeltime = NULL;
lv_obj_t * ui_labeldate = NULL;
lv_obj_t * ui_labelbattery = NULL;
// event funtions

// build funtions

void ui_WatchFace_screen_init(void)
{
    ui_WatchFace = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WatchFace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labeltime = lv_label_create(ui_WatchFace);
    lv_obj_set_width(ui_labeltime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltime, 0);
    lv_obj_set_y(ui_labeltime, -185);
    lv_obj_set_align(ui_labeltime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltime, "09:30");

    ui_labeldate = lv_label_create(ui_WatchFace);
    lv_obj_set_width(ui_labeldate, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_labeldate, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_labeldate, 0);
    lv_obj_set_y(ui_labeldate, -153);
    lv_obj_set_align(ui_labeldate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeldate, "MON 29 JUL");

    ui_labelbattery = lv_label_create(ui_WatchFace);
    lv_obj_set_width(ui_labelbattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelbattery, 156);
    lv_obj_set_y(ui_labelbattery, -222);
    lv_obj_set_align(ui_labelbattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbattery, "82%");

    uic_WatchFace = ui_WatchFace;

}

void ui_WatchFace_screen_destroy(void)
{
    if(ui_WatchFace) lv_obj_del(ui_WatchFace);

    // NULL screen variables
    uic_WatchFace = NULL;
    ui_WatchFace = NULL;
    ui_labeltime = NULL;
    ui_labeldate = NULL;
    ui_labelbattery = NULL;

}
