// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SmartWatch_UI

#ifndef UI_XIAOZHI_H
#define UI_XIAOZHI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_XiaoZhi
extern void ui_XiaoZhi_screen_init(void);
extern void ui_XiaoZhi_screen_destroy(void);
extern lv_obj_t * ui_XiaoZhi;
// CUSTOM VARIABLES
extern lv_obj_t * uic_XiaoZhi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

