// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

static void clear_panel_style(lv_obj_t *obj)
{
    if(obj == NULL) {
        return;
    }
    lv_obj_set_style_border_width(obj, 0, 0);
    lv_obj_set_style_outline_width(obj, 0, 0);
    lv_obj_set_style_shadow_width(obj, 0, 0);
    lv_obj_set_style_bg_opa(obj, 0, 0);
}

lv_obj_t * ui_watch_digital = NULL;
lv_obj_t * ui_bg_1 = NULL;
lv_obj_t * ui_hour_group = NULL;
lv_obj_t * ui_label_hour_1 = NULL;
lv_obj_t * ui_label_hour_2 = NULL;
lv_obj_t * ui_label_min = NULL;
lv_obj_t * ui_battery_group = NULL;
lv_obj_t * ui_date_group = NULL;
lv_obj_t * ui_weather_group_1 = NULL;
lv_obj_t * ui_weather_title_group_1 = NULL;
lv_obj_t * ui_step_group = NULL;
lv_obj_t * ui_daily_mission_group = NULL;
lv_obj_t * ui_button_top = NULL;
lv_obj_t * ui_button_down = NULL;
lv_obj_t * ui_sec_dot = NULL;
lv_obj_t * ui_weather_dots_group2 = NULL;
lv_obj_t * ui_dot14 = NULL;
lv_obj_t * ui_dot15 = NULL;
// event funtions
void ui_event_watch_digital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        left_Animation(ui_hour_group, 0);
        right_Animation(ui_label_min, 0);
        opa_on_Animation(ui_weather_group_1, 300);
        opa_on_Animation(ui_date_group, 500);
        opa_on_Animation(ui_weather_title_group_1, 400);
    }
}

void ui_event_button_top_buttontop(lv_event_t * e)
{
    LV_UNUSED(e);
}

void ui_event_button_down_buttondown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
    }
}

// build funtions

void ui_watch_digital_screen_init(void)
{
    ui_watch_digital = lv_obj_create(NULL);
    lv_obj_set_size(ui_watch_digital, 410, 502);
    lv_obj_remove_flag(ui_watch_digital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_digital, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_1 = lv_image_create(ui_watch_digital);
    lv_image_set_src(ui_bg_1, &ui_img_bg1_png);
    lv_obj_set_width(ui_bg_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_1, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_bg_1, -10);
    lv_obj_add_flag(ui_bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_opa(ui_bg_1, 96, 0);

    ui_hour_group = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_hour_group, 289);
    lv_obj_set_height(ui_hour_group, 222);
    lv_obj_set_x(ui_hour_group, 26);
    lv_obj_set_y(ui_hour_group, 116);
    lv_obj_set_align(ui_hour_group, LV_ALIGN_TOP_LEFT);
    lv_obj_remove_flag(ui_hour_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hour_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    clear_panel_style(ui_hour_group);

    ui_label_hour_1 = lv_label_create(ui_hour_group);
    lv_obj_set_width(ui_label_hour_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_hour_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_hour_1, -23);
    lv_obj_set_y(ui_label_hour_1, 60);
    lv_label_set_text(ui_label_hour_1, "0");
    lv_obj_set_style_text_color(ui_label_hour_1, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_hour_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_hour_1, &ui_font_Number_extra, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_hour_2 = lv_label_create(ui_hour_group);
    lv_obj_set_width(ui_label_hour_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_hour_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_hour_2, 93);
    lv_obj_set_y(ui_label_hour_2, 60);
    lv_label_set_text(ui_label_hour_2, "3");
    lv_obj_set_style_text_color(ui_label_hour_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_hour_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_hour_2, &ui_font_Number_extra, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_min = lv_label_create(ui_watch_digital);
    lv_obj_set_width(ui_label_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_min, 258);
    lv_obj_set_y(ui_label_min, 184);
    lv_obj_set_align(ui_label_min, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_label_min, "27");
    lv_obj_set_style_text_color(ui_label_min, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_min, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_group = ui_batterygroup_create(ui_watch_digital);
    lv_obj_set_x(ui_battery_group, -22);
    lv_obj_set_y(ui_battery_group, 18);
    lv_obj_set_align(ui_battery_group, LV_ALIGN_TOP_RIGHT);
    clear_panel_style(ui_battery_group);

    ui_date_group = ui_dategroup_create(ui_watch_digital);
    lv_obj_set_x(ui_date_group, 24);
    lv_obj_set_y(ui_date_group, 16);
    lv_obj_set_align(ui_date_group, LV_ALIGN_TOP_LEFT);
    clear_panel_style(ui_date_group);
    lv_obj_set_width(ui_date_group, 110);
    lv_obj_set_height(ui_date_group, 72);
    lv_obj_set_style_pad_row(ui_date_group, 2, 0);
    lv_obj_set_align(ui_comp_get_child(ui_date_group, UI_COMP_DATEGROUP_DAY), LV_ALIGN_TOP_LEFT);
    lv_obj_set_align(ui_comp_get_child(ui_date_group, UI_COMP_DATEGROUP_MONTH), LV_ALIGN_LEFT_MID);
    lv_obj_set_align(ui_comp_get_child(ui_date_group, UI_COMP_DATEGROUP_YEAR), LV_ALIGN_BOTTOM_LEFT);

    ui_weather_group_1 = ui_weathergroup1_create(ui_watch_digital);
    lv_obj_set_x(ui_weather_group_1, 24);
    lv_obj_set_y(ui_weather_group_1, 102);
    lv_obj_set_align(ui_weather_group_1, LV_ALIGN_TOP_LEFT);
    clear_panel_style(ui_weather_group_1);

    lv_image_set_src(ui_comp_get_child(ui_weather_group_1, UI_COMP_WEATHERGROUP1_CLOUD_FOG_1),
                     &ui_img_weather_sun_cloud_png);

    ui_weather_title_group_1 = ui_titlegroup_create(ui_watch_digital);
    lv_obj_set_width(ui_weather_title_group_1, 170);
    lv_obj_set_height(ui_weather_title_group_1, 56);
    lv_obj_set_x(ui_weather_title_group_1, -26);
    lv_obj_set_y(ui_weather_title_group_1, 18);
    lv_obj_set_align(ui_weather_title_group_1, LV_ALIGN_TOP_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_TITLE), "Partly Cloudy");
    lv_label_set_text(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), "Max 18 Min 12");
    lv_obj_set_width(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_TITLE), 170);
    lv_obj_set_width(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), 170);
    lv_label_set_long_mode(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_TITLE), LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_long_mode(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), LV_LABEL_LONG_MODE_CLIP);
    lv_obj_set_style_text_align(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_TITLE), LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_align(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_align(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_TITLE), LV_ALIGN_TOP_LEFT);
    lv_obj_set_align(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_x(ui_comp_get_child(ui_weather_title_group_1, UI_COMP_TITLEGROUP_SUBTITLE), 0);
    clear_panel_style(ui_weather_title_group_1);

    ui_step_group = ui_stepgroup_create(ui_watch_digital);
    lv_obj_set_x(ui_step_group, 28);
    lv_obj_set_y(ui_step_group, -146);
    lv_obj_set_align(ui_step_group, LV_ALIGN_BOTTOM_LEFT);
    clear_panel_style(ui_step_group);

    ui_daily_mission_group = ui_dailymissiongroup_create(ui_watch_digital);
    clear_panel_style(ui_daily_mission_group);
    lv_obj_add_flag(ui_daily_mission_group, LV_OBJ_FLAG_HIDDEN);

    ui_button_top = ui_buttontop_create(ui_watch_digital);
    lv_obj_add_flag(ui_button_top, LV_OBJ_FLAG_HIDDEN);
    clear_panel_style(ui_button_top);

    ui_button_down = ui_buttondown_create(ui_watch_digital);
    lv_obj_set_x(ui_button_down, -26);
    lv_obj_set_y(ui_button_down, -24);
    lv_obj_set_align(ui_button_down, LV_ALIGN_BOTTOM_RIGHT);
    clear_panel_style(ui_button_down);
    lv_obj_set_style_bg_opa(ui_button_down, 255, 0);
    lv_obj_set_style_bg_color(ui_button_down, lv_color_hex(0x111111), 0);
    lv_obj_set_style_radius(ui_button_down, 24, 0);
    lv_obj_set_size(ui_button_down, 92, 52);

    ui_sec_dot = lv_image_create(ui_watch_digital);
    lv_image_set_src(ui_sec_dot, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_sec_dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec_dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec_dot, 0);
    lv_obj_set_y(ui_sec_dot, 30);
    lv_obj_set_align(ui_sec_dot, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_sec_dot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_sec_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_sec_dot, 4, 194);
    lv_obj_add_flag(ui_sec_dot, LV_OBJ_FLAG_HIDDEN);

    ui_weather_dots_group2 = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_weather_dots_group2, 20);
    lv_obj_set_height(ui_weather_dots_group2, 50);
    lv_obj_set_x(ui_weather_dots_group2, -24);
    lv_obj_set_y(ui_weather_dots_group2, -92);
    lv_obj_set_align(ui_weather_dots_group2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_weather_dots_group2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_weather_dots_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weather_dots_group2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather_dots_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather_dots_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_weather_dots_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_weather_dots_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    clear_panel_style(ui_weather_dots_group2);

    ui_dot14 = lv_obj_create(ui_weather_dots_group2);
    lv_obj_set_width(ui_dot14, 10);
    lv_obj_set_height(ui_dot14, 10);
    lv_obj_set_align(ui_dot14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot15 = lv_obj_create(ui_weather_dots_group2);
    lv_obj_set_width(ui_dot15, 6);
    lv_obj_set_height(ui_dot15, 6);
    lv_obj_set_align(ui_dot15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot15, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_weather_dots_group2, LV_OBJ_FLAG_HIDDEN);

    lv_obj_move_foreground(ui_button_down);

    lv_obj_add_event_cb(ui_button_top, ui_event_button_top_buttontop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_down, ui_event_button_down_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watch_digital, ui_event_watch_digital, LV_EVENT_ALL, NULL);

}

void ui_watch_digital_screen_destroy(void)
{
    if(ui_watch_digital) lv_obj_del(ui_watch_digital);

    // NULL screen variables
    ui_watch_digital = NULL;
    ui_bg_1 = NULL;
    ui_hour_group = NULL;
    ui_label_hour_1 = NULL;
    ui_label_hour_2 = NULL;
    ui_label_min = NULL;
    ui_battery_group = NULL;
    ui_date_group = NULL;
    ui_weather_group_1 = NULL;
    ui_weather_title_group_1 = NULL;
    ui_step_group = NULL;
    ui_daily_mission_group = NULL;
    ui_button_top = NULL;
    ui_button_down = NULL;
    ui_sec_dot = NULL;
    ui_weather_dots_group2 = NULL;
    ui_dot14 = NULL;
    ui_dot15 = NULL;

}
